# vim:ft=kitty

## name:     LucyGRUB Crimson
## source:   LucyGRUB terminal theme
## blurb:    Black/crimson terminal palette with hot-pink focus.



# The basic colors
foreground              #E6D1D7
background              #1A1A1A
selection_foreground    #FFF4F7
selection_background    #A4133C

# Cursor colors
cursor                  #FB6F92
cursor_text_color       #1A1A1A

# URL underline color when hovering with mouse
url_color               #FB6F92

# Kitty window border colors
active_border_color     #A4133C
inactive_border_color   #4D2731
bell_border_color       #FB6F92

# OS Window titlebar colors
wayland_titlebar_color background
macos_titlebar_color background

# Tab bar colors
active_tab_foreground   #A4133C
active_tab_background   #1A1A1A
inactive_tab_foreground #A4133C
inactive_tab_background #1A1A1A
tab_bar_background      #101010

# Colors for marks (marked text in the terminal)
mark1_foreground #FFF4F7
mark1_background #A4133C
mark2_foreground #1A1A1A
mark2_background #FB6F92
mark3_foreground #FFF4F7
mark3_background #6F283D

# The 16 terminal colors

# black
color0 #1A1A1A
color8 #594047

# red
color1 #A4133C
color9 #FB6F92

# green
color2  #8E9C72
color10 #B3C58D

# yellow
color3  #C28F5C
color11 #E5B477

# blue
color4  #6F829E
color12 #91A9CB

# magenta
color5  #A94E6A
color13 #E37899

# cyan
color6  #658F8C
color14 #8ABBB6

# white
color7  #C9B6BB
color15 #FFF4F7
